version: "3"

vars:
  APP_NAME: multitenant-db
  BIN_DIR: bin
  MAIN_PATH: ./cmd/multi-tenant-db

tasks:
  # Unit testing
  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test-short:
    desc: Run tests excluding integration tests
    cmds:
      - go test -v ./cmd/...

  coverage:
    desc: Run tests with coverage and generate lcov.info
    cmds:
      - echo "Running tests with coverage..."
      - go test -coverprofile=coverage.out ./...
      - echo "Converting coverage to lcov format..."
      - gcov2lcov -infile=coverage.out -outfile=lcov.info
      - echo "Coverage summary:"
      - go tool cover -func=coverage.out | grep total
      - echo "✅ Coverage files generated (coverage.out, lcov.info)"

  coverage-html:
    desc: Run tests with coverage and open HTML report
    deps: [coverage]
    cmds:
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Opening coverage.html..."
      - cmd: open coverage.html
        platforms: [darwin]
      - cmd: xdg-open coverage.html
        platforms: [linux]

  # Building
  build:
    desc: Build the application
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/{{.APP_NAME}} {{.MAIN_PATH}}

  build-release:
    desc: Build the application with release flags
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -ldflags="-s -w" -o {{.BIN_DIR}}/{{.APP_NAME}} {{.MAIN_PATH}}

  # Running
  run:
    desc: Build and run the application
    deps: [build]
    cmds:
      - ./{{.BIN_DIR}}/{{.APP_NAME}}

  dev:
    desc: Run the application directly without building
    cmds:
      - go run {{.MAIN_PATH}}

  # Maintenance
  clean:
    desc: Clean build artifacts and coverage files
    cmds:
      - rm -f {{.APP_NAME}} multi-tenant-db ephemeral-db coverage.out lcov.info coverage.html
      - rm -rf {{.BIN_DIR}}/
      - rm -f integration-server.log integration-server.pid

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  # Tools
  install-tools:
    desc: Install required development tools
    cmds:
      - go install github.com/jandelgado/gcov2lcov@latest
