// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Welcome message for Multitenant DB API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "root"
                ],
                "summary": "Root welcome",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        },
        "/api/databases": {
            "get": {
                "description": "List, create, or delete tenant databases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Manage tenant databases",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant idx (for DELETE)",
                        "name": "idx",
                        "in": "query"
                    },
                    {
                        "description": "Create database request (for POST)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List/Delete success",
                        "schema": {
                            "$ref": "#/definitions/api.DatabaseResponse"
                        }
                    },
                    "201": {
                        "description": "Create success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "List, create, or delete tenant databases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Manage tenant databases",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant idx (for DELETE)",
                        "name": "idx",
                        "in": "query"
                    },
                    {
                        "description": "Create database request (for POST)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List/Delete success",
                        "schema": {
                            "$ref": "#/definitions/api.DatabaseResponse"
                        }
                    },
                    "201": {
                        "description": "Create success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "List, create, or delete tenant databases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "databases"
                ],
                "summary": "Manage tenant databases",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant idx (for DELETE)",
                        "name": "idx",
                        "in": "query"
                    },
                    {
                        "description": "Create database request (for POST)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/api.CreateDatabaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List/Delete success",
                        "schema": {
                            "$ref": "#/definitions/api.DatabaseResponse"
                        }
                    },
                    "201": {
                        "description": "Create success",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "405": {
                        "description": "Method not allowed",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/info": {
            "get": {
                "description": "Returns API and protocol information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "API info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateDatabaseRequest": {
            "type": "object",
            "properties": {
                "idx": {
                    "type": "string"
                }
            }
        },
        "api.DatabaseInfo": {
            "type": "object",
            "properties": {
                "idx": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "api.DatabaseResponse": {
            "type": "object",
            "properties": {
                "databases": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DatabaseInfo"
                    }
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "api.Response": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
